using System.Collections.Generic;

// 이 파일은 ItemImporter에 의해 자동 생성됩니다.
// 고정 Enum은 CoreDefinitions.cs를 확인하세요.

/// <summary>
/// Defines the high-level categories for items in the G.S.I project.
/// </summary>
public enum ItemMainCategory
{
    None,
    Consumable,
    Crafting,
    CurrencyToken,
    DocumentInformation,
    Enhancement,
    Equipment,
    HousingPlacement,
    LifeSkill,
    Material,
    MountVehicle,
    PetSummon,
    Quest,
    SpecialSystem
}

public enum ItemMiddleCategory
{
    None,
    BoostConsumable,
    CombatConsumable,
    DocumentConsumable,
    LifeConsumable,
    RecoveryConsumable,
    TravelConsumable,
    CraftingComponent,
    CraftingDesign,
    CraftingSupport,
    Recipe,
    BaseCurrency,
    EntryMedium,
    ExchangeToken,
    SpecialCurrency,
    GeneralDocument,
    KnowledgeDocument,
    LicenseDocument,
    MapIntel,
    AdvancementMaterial,
    EmbeddedEnhancement,
    EnhancementStone,
    OptionMaterial,
    RecoveryRepair,
    Accessory,
    Armor,
    EquipSupport,
    Weapon,
    BuildingPart,
    Decoration,
    FunctionalFacility,
    Furniture,
    FarmingBreeding,
    GatheringTool,
    LifeProduct,
    ProductionTool,
    CreatureMaterial,
    MineralMaterial,
    NaturalMaterial,
    ProcessedMaterial,
    SpecialMaterial,
    MountContract,
    MountEquipment,
    TravelModule,
    EvolutionItem,
    GrowthItem,
    PetContract,
    SummonEquipment,
    CommonQuest,
    FactionQuest,
    MainQuest,
    RepeatableQuest,
    Event,
    OperationTool,
    Premium,
    SystemOnly
}

public enum ItemSubCategory
{
    None,
    CombatBoost,
    DropBoost,
    EXPBoost,
    StatBoost,
    Deployable,
    Explosive,
    ThrownItem,
    Trap,
    ContractPaper,
    Scroll,
    SpellScroll,
    SummonScroll,
    Bait,
    Drink,
    Food,
    Fuel,
    HPRecovery,
    MPRecovery,
    Revival,
    StatusRecovery,
    LocationMarkingItem,
    MobilitySupport,
    ReturnItem,
    TeleportItem,
    CorePart,
    FramePart,
    LinkPart,
    SubPart,
    AccessoryBlueprint,
    ArmorBlueprint,
    MechanismBlueprint,
    WeaponBlueprint,
    Binder,
    Catalyst,
    Solvent,
    Stabilizer,
    AlchemyRecipe,
    BlacksmithingRecipe,
    CookingRecipe,
    TailoringRecipe,
    CopperCoin,
    Gold,
    LocalCurrency,
    Silver,
    DimensionalPass,
    Key,
    Ticket,
    TreasureMap,
    DungeonToken,
    EventToken,
    PvPToken,
    RaidToken,
    ContributionPoint,
    HonorPoint,
    PremiumCurrency,
    SeasonCurrency,
    Letter,
    Logbook,
    Record,
    Report,
    Compendium,
    ResearchNote,
    SkillBook,
    SpellTome,
    Certificate,
    Deed,
    Pass,
    Permit,
    CipherText,
    ExplorationRecord,
    Map,
    SeaChart,
    AwakeningMaterial,
    BreakthroughMaterial,
    EvolutionMaterial,
    TranscendenceMaterial,
    Gem,
    Insignia,
    MagicStone,
    Rune,
    AccessoryStone,
    ArmorStone,
    UniversalStone,
    WeaponStone,
    OptionConversionMaterial,
    OptionLockMaterial,
    ReappraisalMaterial,
    SocketMaterial,
    DurabilityRecovery,
    MaintenancePart,
    RepairTool,
    RestorationMaterial,
    Bracelet,
    CharmEmblem,
    Earring,
    Necklace,
    Ring,
    WaistAccessory,
    BodyArmor,
    CapeOuterwear,
    FootArmor,
    HandArmor,
    HeadArmor,
    LegArmor,
    Shield,
    ShoulderArmor,
    Ammo,
    EquipmentPart,
    MountEquipment,
    PetEquipment,
    WeaponAttachment,
    ArcaneFocus,
    Axe,
    Bow,
    Crossbow,
    Dagger,
    Firearm,
    Mace,
    Spear,
    SpecialWeapon,
    Staff,
    Sword,
    Wand,
    CeilingPart,
    DoorWindowPart,
    FloorPart,
    WallPart,
    FloorDecoration,
    GardenDecoration,
    Ornament,
    WallDecoration,
    AlchemyStation,
    CookingStation,
    CraftingStation,
    StorageFacility,
    BedroomFurniture,
    DisplayFurniture,
    LivingRoomFurniture,
    StorageFurniture,
    Feed,
    Fertilizer,
    Sapling,
    Seed,
    FishingTool,
    HerbalismTool,
    LoggingTool,
    MiningTool,
    AgedProduct,
    Catch,
    Harvest,
    ProcessedProduct,
    AlchemyTool,
    BlacksmithTool,
    CookingTool,
    TailoringTool,
    CommonPart,
    MagicalOrgan,
    RarePart,
    ToxicPart,
    Crystal,
    MetalMineral,
    Powder,
    RoughGem,
    BoneShell,
    Fiber,
    Herb,
    Leather,
    Liquid,
    Ore,
    Wood,
    AlchemyBase,
    RefinedMaterial,
    SmeltedMaterial,
    TextileMaterial,
    WoodworkingMaterial,
    BossMaterial,
    RaidMaterial,
    RegionalSpecialty,
    RelicFragment,
    AquaticMount,
    FlyingMount,
    GroundMount,
    SpecialMount,
    Barding,
    PropulsionGear,
    Rein,
    Saddle,
    FallDevice,
    FloatDevice,
    Glider,
    PropelTool,
    AppearanceShiftMaterial,
    EvolutionStone,
    RankUpMaterial,
    AffinityItem,
    GrowthMaterial,
    SkillManual,
    Contract,
    PetEgg,
    SpiritSeal,
    SummonCore,
    PetAccessory,
    PetArmor,
    PetWeapon,
    SummonSupportGear,
    CollectionRequestItem,
    DeliveryItem,
    EvidenceItem,
    TrophyProof,
    FactionToken,
    GuildContributionItem,
    ReputationItem,
    WarSupply,
    KeyRelic,
    RitualMaterial,
    StoryDocument,
    UnsealingItem,
    DailyRequestItem,
    DeliveryBox,
    RepeatToken,
    WeeklyRequestItem,
    AttendanceReward,
    CollaborationItem,
    CommemorativeItem,
    SeasonItem,
    CompensationItem,
    DebugItem,
    GMItem,
    TestItem,
    AppearanceTicket,
    Costume,
    ExpansionTicket,
    NameChangeTicket,
    AchievementReward,
    MailAttachment,
    TemporaryUndefinedItem,
    TutorialItem
}

public static class CategoryDefinitionMaps
{
    public static readonly Dictionary<ItemMainCategory, ItemMiddleCategory[]> MainToMiddleMap =
        new Dictionary<ItemMainCategory, ItemMiddleCategory[]>
        {
            { ItemMainCategory.None, new[] { ItemMiddleCategory.None } },
            { ItemMainCategory.Consumable, new[] { ItemMiddleCategory.None, ItemMiddleCategory.BoostConsumable, ItemMiddleCategory.CombatConsumable, ItemMiddleCategory.DocumentConsumable, ItemMiddleCategory.LifeConsumable, ItemMiddleCategory.RecoveryConsumable, ItemMiddleCategory.TravelConsumable } },
            { ItemMainCategory.Crafting, new[] { ItemMiddleCategory.None, ItemMiddleCategory.CraftingComponent, ItemMiddleCategory.CraftingDesign, ItemMiddleCategory.CraftingSupport, ItemMiddleCategory.Recipe } },
            { ItemMainCategory.CurrencyToken, new[] { ItemMiddleCategory.None, ItemMiddleCategory.BaseCurrency, ItemMiddleCategory.EntryMedium, ItemMiddleCategory.ExchangeToken, ItemMiddleCategory.SpecialCurrency } },
            { ItemMainCategory.DocumentInformation, new[] { ItemMiddleCategory.None, ItemMiddleCategory.GeneralDocument, ItemMiddleCategory.KnowledgeDocument, ItemMiddleCategory.LicenseDocument, ItemMiddleCategory.MapIntel } },
            { ItemMainCategory.Enhancement, new[] { ItemMiddleCategory.None, ItemMiddleCategory.AdvancementMaterial, ItemMiddleCategory.EmbeddedEnhancement, ItemMiddleCategory.EnhancementStone, ItemMiddleCategory.OptionMaterial, ItemMiddleCategory.RecoveryRepair } },
            { ItemMainCategory.Equipment, new[] { ItemMiddleCategory.None, ItemMiddleCategory.Accessory, ItemMiddleCategory.Armor, ItemMiddleCategory.EquipSupport, ItemMiddleCategory.Weapon } },
            { ItemMainCategory.HousingPlacement, new[] { ItemMiddleCategory.None, ItemMiddleCategory.BuildingPart, ItemMiddleCategory.Decoration, ItemMiddleCategory.FunctionalFacility, ItemMiddleCategory.Furniture } },
            { ItemMainCategory.LifeSkill, new[] { ItemMiddleCategory.None, ItemMiddleCategory.FarmingBreeding, ItemMiddleCategory.GatheringTool, ItemMiddleCategory.LifeProduct, ItemMiddleCategory.ProductionTool } },
            { ItemMainCategory.Material, new[] { ItemMiddleCategory.None, ItemMiddleCategory.CreatureMaterial, ItemMiddleCategory.MineralMaterial, ItemMiddleCategory.NaturalMaterial, ItemMiddleCategory.ProcessedMaterial, ItemMiddleCategory.SpecialMaterial } },
            { ItemMainCategory.MountVehicle, new[] { ItemMiddleCategory.None, ItemMiddleCategory.MountContract, ItemMiddleCategory.MountEquipment, ItemMiddleCategory.TravelModule } },
            { ItemMainCategory.PetSummon, new[] { ItemMiddleCategory.None, ItemMiddleCategory.EvolutionItem, ItemMiddleCategory.GrowthItem, ItemMiddleCategory.PetContract, ItemMiddleCategory.SummonEquipment } },
            { ItemMainCategory.Quest, new[] { ItemMiddleCategory.None, ItemMiddleCategory.CommonQuest, ItemMiddleCategory.FactionQuest, ItemMiddleCategory.MainQuest, ItemMiddleCategory.RepeatableQuest } },
            { ItemMainCategory.SpecialSystem, new[] { ItemMiddleCategory.None, ItemMiddleCategory.Event, ItemMiddleCategory.OperationTool, ItemMiddleCategory.Premium, ItemMiddleCategory.SystemOnly } }
        };

    public static readonly Dictionary<ItemMiddleCategory, ItemSubCategory[]> MiddleToSubMap =
        new Dictionary<ItemMiddleCategory, ItemSubCategory[]>
        {
            { ItemMiddleCategory.None, new[] { ItemSubCategory.None } },
            { ItemMiddleCategory.BoostConsumable, new[] { ItemSubCategory.None, ItemSubCategory.CombatBoost, ItemSubCategory.DropBoost, ItemSubCategory.EXPBoost, ItemSubCategory.StatBoost } },
            { ItemMiddleCategory.CombatConsumable, new[] { ItemSubCategory.None, ItemSubCategory.Deployable, ItemSubCategory.Explosive, ItemSubCategory.ThrownItem, ItemSubCategory.Trap } },
            { ItemMiddleCategory.DocumentConsumable, new[] { ItemSubCategory.None, ItemSubCategory.ContractPaper, ItemSubCategory.Scroll, ItemSubCategory.SpellScroll, ItemSubCategory.SummonScroll } },
            { ItemMiddleCategory.LifeConsumable, new[] { ItemSubCategory.None, ItemSubCategory.Bait, ItemSubCategory.Drink, ItemSubCategory.Food, ItemSubCategory.Fuel } },
            { ItemMiddleCategory.RecoveryConsumable, new[] { ItemSubCategory.None, ItemSubCategory.HPRecovery, ItemSubCategory.MPRecovery, ItemSubCategory.Revival, ItemSubCategory.StatusRecovery } },
            { ItemMiddleCategory.TravelConsumable, new[] { ItemSubCategory.None, ItemSubCategory.LocationMarkingItem, ItemSubCategory.MobilitySupport, ItemSubCategory.ReturnItem, ItemSubCategory.TeleportItem } },
            { ItemMiddleCategory.CraftingComponent, new[] { ItemSubCategory.None, ItemSubCategory.CorePart, ItemSubCategory.FramePart, ItemSubCategory.LinkPart, ItemSubCategory.SubPart } },
            { ItemMiddleCategory.CraftingDesign, new[] { ItemSubCategory.None, ItemSubCategory.AccessoryBlueprint, ItemSubCategory.ArmorBlueprint, ItemSubCategory.MechanismBlueprint, ItemSubCategory.WeaponBlueprint } },
            { ItemMiddleCategory.CraftingSupport, new[] { ItemSubCategory.None, ItemSubCategory.Binder, ItemSubCategory.Catalyst, ItemSubCategory.Solvent, ItemSubCategory.Stabilizer } },
            { ItemMiddleCategory.Recipe, new[] { ItemSubCategory.None, ItemSubCategory.AlchemyRecipe, ItemSubCategory.BlacksmithingRecipe, ItemSubCategory.CookingRecipe, ItemSubCategory.TailoringRecipe } },
            { ItemMiddleCategory.BaseCurrency, new[] { ItemSubCategory.None, ItemSubCategory.CopperCoin, ItemSubCategory.Gold, ItemSubCategory.LocalCurrency, ItemSubCategory.Silver } },
            { ItemMiddleCategory.EntryMedium, new[] { ItemSubCategory.None, ItemSubCategory.DimensionalPass, ItemSubCategory.Key, ItemSubCategory.Ticket, ItemSubCategory.TreasureMap } },
            { ItemMiddleCategory.ExchangeToken, new[] { ItemSubCategory.None, ItemSubCategory.DungeonToken, ItemSubCategory.EventToken, ItemSubCategory.PvPToken, ItemSubCategory.RaidToken } },
            { ItemMiddleCategory.SpecialCurrency, new[] { ItemSubCategory.None, ItemSubCategory.ContributionPoint, ItemSubCategory.HonorPoint, ItemSubCategory.PremiumCurrency, ItemSubCategory.SeasonCurrency } },
            { ItemMiddleCategory.GeneralDocument, new[] { ItemSubCategory.None, ItemSubCategory.Letter, ItemSubCategory.Logbook, ItemSubCategory.Record, ItemSubCategory.Report } },
            { ItemMiddleCategory.KnowledgeDocument, new[] { ItemSubCategory.None, ItemSubCategory.Compendium, ItemSubCategory.ResearchNote, ItemSubCategory.SkillBook, ItemSubCategory.SpellTome } },
            { ItemMiddleCategory.LicenseDocument, new[] { ItemSubCategory.None, ItemSubCategory.Certificate, ItemSubCategory.Deed, ItemSubCategory.Pass, ItemSubCategory.Permit } },
            { ItemMiddleCategory.MapIntel, new[] { ItemSubCategory.None, ItemSubCategory.CipherText, ItemSubCategory.ExplorationRecord, ItemSubCategory.Map, ItemSubCategory.SeaChart } },
            { ItemMiddleCategory.AdvancementMaterial, new[] { ItemSubCategory.None, ItemSubCategory.AwakeningMaterial, ItemSubCategory.BreakthroughMaterial, ItemSubCategory.EvolutionMaterial, ItemSubCategory.TranscendenceMaterial } },
            { ItemMiddleCategory.EmbeddedEnhancement, new[] { ItemSubCategory.None, ItemSubCategory.Gem, ItemSubCategory.Insignia, ItemSubCategory.MagicStone, ItemSubCategory.Rune } },
            { ItemMiddleCategory.EnhancementStone, new[] { ItemSubCategory.None, ItemSubCategory.AccessoryStone, ItemSubCategory.ArmorStone, ItemSubCategory.UniversalStone, ItemSubCategory.WeaponStone } },
            { ItemMiddleCategory.OptionMaterial, new[] { ItemSubCategory.None, ItemSubCategory.OptionConversionMaterial, ItemSubCategory.OptionLockMaterial, ItemSubCategory.ReappraisalMaterial, ItemSubCategory.SocketMaterial } },
            { ItemMiddleCategory.RecoveryRepair, new[] { ItemSubCategory.None, ItemSubCategory.DurabilityRecovery, ItemSubCategory.MaintenancePart, ItemSubCategory.RepairTool, ItemSubCategory.RestorationMaterial } },
            { ItemMiddleCategory.Accessory, new[] { ItemSubCategory.None, ItemSubCategory.Bracelet, ItemSubCategory.CharmEmblem, ItemSubCategory.Earring, ItemSubCategory.Necklace, ItemSubCategory.Ring, ItemSubCategory.WaistAccessory } },
            { ItemMiddleCategory.Armor, new[] { ItemSubCategory.None, ItemSubCategory.BodyArmor, ItemSubCategory.CapeOuterwear, ItemSubCategory.FootArmor, ItemSubCategory.HandArmor, ItemSubCategory.HeadArmor, ItemSubCategory.LegArmor, ItemSubCategory.Shield, ItemSubCategory.ShoulderArmor } },
            { ItemMiddleCategory.EquipSupport, new[] { ItemSubCategory.None, ItemSubCategory.Ammo, ItemSubCategory.EquipmentPart, ItemSubCategory.MountEquipment, ItemSubCategory.PetEquipment, ItemSubCategory.WeaponAttachment } },
            { ItemMiddleCategory.Weapon, new[] { ItemSubCategory.None, ItemSubCategory.ArcaneFocus, ItemSubCategory.Axe, ItemSubCategory.Bow, ItemSubCategory.Crossbow, ItemSubCategory.Dagger, ItemSubCategory.Firearm, ItemSubCategory.Mace, ItemSubCategory.Spear, ItemSubCategory.SpecialWeapon, ItemSubCategory.Staff, ItemSubCategory.Sword, ItemSubCategory.Wand } },
            { ItemMiddleCategory.BuildingPart, new[] { ItemSubCategory.None, ItemSubCategory.CeilingPart, ItemSubCategory.DoorWindowPart, ItemSubCategory.FloorPart, ItemSubCategory.WallPart } },
            { ItemMiddleCategory.Decoration, new[] { ItemSubCategory.None, ItemSubCategory.FloorDecoration, ItemSubCategory.GardenDecoration, ItemSubCategory.Ornament, ItemSubCategory.WallDecoration } },
            { ItemMiddleCategory.FunctionalFacility, new[] { ItemSubCategory.None, ItemSubCategory.AlchemyStation, ItemSubCategory.CookingStation, ItemSubCategory.CraftingStation, ItemSubCategory.StorageFacility } },
            { ItemMiddleCategory.Furniture, new[] { ItemSubCategory.None, ItemSubCategory.BedroomFurniture, ItemSubCategory.DisplayFurniture, ItemSubCategory.LivingRoomFurniture, ItemSubCategory.StorageFurniture } },
            { ItemMiddleCategory.FarmingBreeding, new[] { ItemSubCategory.None, ItemSubCategory.Feed, ItemSubCategory.Fertilizer, ItemSubCategory.Sapling, ItemSubCategory.Seed } },
            { ItemMiddleCategory.GatheringTool, new[] { ItemSubCategory.None, ItemSubCategory.FishingTool, ItemSubCategory.HerbalismTool, ItemSubCategory.LoggingTool, ItemSubCategory.MiningTool } },
            { ItemMiddleCategory.LifeProduct, new[] { ItemSubCategory.None, ItemSubCategory.AgedProduct, ItemSubCategory.Catch, ItemSubCategory.Harvest, ItemSubCategory.ProcessedProduct } },
            { ItemMiddleCategory.ProductionTool, new[] { ItemSubCategory.None, ItemSubCategory.AlchemyTool, ItemSubCategory.BlacksmithTool, ItemSubCategory.CookingTool, ItemSubCategory.TailoringTool } },
            { ItemMiddleCategory.CreatureMaterial, new[] { ItemSubCategory.None, ItemSubCategory.CommonPart, ItemSubCategory.MagicalOrgan, ItemSubCategory.RarePart, ItemSubCategory.ToxicPart } },
            { ItemMiddleCategory.MineralMaterial, new[] { ItemSubCategory.None, ItemSubCategory.Crystal, ItemSubCategory.MetalMineral, ItemSubCategory.Powder, ItemSubCategory.RoughGem } },
            { ItemMiddleCategory.NaturalMaterial, new[] { ItemSubCategory.None, ItemSubCategory.BoneShell, ItemSubCategory.Fiber, ItemSubCategory.Herb, ItemSubCategory.Leather, ItemSubCategory.Liquid, ItemSubCategory.Ore, ItemSubCategory.Wood } },
            { ItemMiddleCategory.ProcessedMaterial, new[] { ItemSubCategory.None, ItemSubCategory.AlchemyBase, ItemSubCategory.RefinedMaterial, ItemSubCategory.SmeltedMaterial, ItemSubCategory.TextileMaterial, ItemSubCategory.WoodworkingMaterial } },
            { ItemMiddleCategory.SpecialMaterial, new[] { ItemSubCategory.None, ItemSubCategory.BossMaterial, ItemSubCategory.RaidMaterial, ItemSubCategory.RegionalSpecialty, ItemSubCategory.RelicFragment } },
            { ItemMiddleCategory.MountContract, new[] { ItemSubCategory.None, ItemSubCategory.AquaticMount, ItemSubCategory.FlyingMount, ItemSubCategory.GroundMount, ItemSubCategory.SpecialMount } },
            { ItemMiddleCategory.MountEquipment, new[] { ItemSubCategory.None, ItemSubCategory.Barding, ItemSubCategory.PropulsionGear, ItemSubCategory.Rein, ItemSubCategory.Saddle } },
            { ItemMiddleCategory.TravelModule, new[] { ItemSubCategory.None, ItemSubCategory.FallDevice, ItemSubCategory.FloatDevice, ItemSubCategory.Glider, ItemSubCategory.PropelTool } },
            { ItemMiddleCategory.EvolutionItem, new[] { ItemSubCategory.None, ItemSubCategory.AppearanceShiftMaterial, ItemSubCategory.AwakeningMaterial, ItemSubCategory.EvolutionStone, ItemSubCategory.RankUpMaterial } },
            { ItemMiddleCategory.GrowthItem, new[] { ItemSubCategory.None, ItemSubCategory.AffinityItem, ItemSubCategory.Feed, ItemSubCategory.GrowthMaterial, ItemSubCategory.SkillManual } },
            { ItemMiddleCategory.PetContract, new[] { ItemSubCategory.None, ItemSubCategory.Contract, ItemSubCategory.PetEgg, ItemSubCategory.SpiritSeal, ItemSubCategory.SummonCore } },
            { ItemMiddleCategory.SummonEquipment, new[] { ItemSubCategory.None, ItemSubCategory.PetAccessory, ItemSubCategory.PetArmor, ItemSubCategory.PetWeapon, ItemSubCategory.SummonSupportGear } },
            { ItemMiddleCategory.CommonQuest, new[] { ItemSubCategory.None, ItemSubCategory.CollectionRequestItem, ItemSubCategory.DeliveryItem, ItemSubCategory.EvidenceItem, ItemSubCategory.TrophyProof } },
            { ItemMiddleCategory.FactionQuest, new[] { ItemSubCategory.None, ItemSubCategory.FactionToken, ItemSubCategory.GuildContributionItem, ItemSubCategory.ReputationItem, ItemSubCategory.WarSupply } },
            { ItemMiddleCategory.MainQuest, new[] { ItemSubCategory.None, ItemSubCategory.KeyRelic, ItemSubCategory.RitualMaterial, ItemSubCategory.StoryDocument, ItemSubCategory.UnsealingItem } },
            { ItemMiddleCategory.RepeatableQuest, new[] { ItemSubCategory.None, ItemSubCategory.DailyRequestItem, ItemSubCategory.DeliveryBox, ItemSubCategory.RepeatToken, ItemSubCategory.WeeklyRequestItem } },
            { ItemMiddleCategory.Event, new[] { ItemSubCategory.None, ItemSubCategory.AttendanceReward, ItemSubCategory.CollaborationItem, ItemSubCategory.CommemorativeItem, ItemSubCategory.SeasonItem } },
            { ItemMiddleCategory.OperationTool, new[] { ItemSubCategory.None, ItemSubCategory.CompensationItem, ItemSubCategory.DebugItem, ItemSubCategory.GMItem, ItemSubCategory.TestItem } },
            { ItemMiddleCategory.Premium, new[] { ItemSubCategory.None, ItemSubCategory.AppearanceTicket, ItemSubCategory.Costume, ItemSubCategory.ExpansionTicket, ItemSubCategory.NameChangeTicket } },
            { ItemMiddleCategory.SystemOnly, new[] { ItemSubCategory.None, ItemSubCategory.AchievementReward, ItemSubCategory.MailAttachment, ItemSubCategory.TemporaryUndefinedItem, ItemSubCategory.TutorialItem } }
        };
}
